/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ImageUploader {
        "errorMessage": string;
        "height": number;
        "loading": boolean;
        "successIconHeight": number;
        "uploadLabel": string;
        "uploadSuccess": boolean;
        "width": number;
    }
    interface ImageUploaderWrapper {
    }
}
export interface ImageUploaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLImageUploaderElement;
}
declare global {
    interface HTMLImageUploaderElementEventMap {
        "imageSelected": File;
    }
    interface HTMLImageUploaderElement extends Components.ImageUploader, HTMLStencilElement {
        addEventListener<K extends keyof HTMLImageUploaderElementEventMap>(type: K, listener: (this: HTMLImageUploaderElement, ev: ImageUploaderCustomEvent<HTMLImageUploaderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLImageUploaderElementEventMap>(type: K, listener: (this: HTMLImageUploaderElement, ev: ImageUploaderCustomEvent<HTMLImageUploaderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLImageUploaderElement: {
        prototype: HTMLImageUploaderElement;
        new (): HTMLImageUploaderElement;
    };
    interface HTMLImageUploaderWrapperElement extends Components.ImageUploaderWrapper, HTMLStencilElement {
    }
    var HTMLImageUploaderWrapperElement: {
        prototype: HTMLImageUploaderWrapperElement;
        new (): HTMLImageUploaderWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "image-uploader": HTMLImageUploaderElement;
        "image-uploader-wrapper": HTMLImageUploaderWrapperElement;
    }
}
declare namespace LocalJSX {
    interface ImageUploader {
        "errorMessage"?: string;
        "height"?: number;
        "loading"?: boolean;
        "onImageSelected"?: (event: ImageUploaderCustomEvent<File>) => void;
        "successIconHeight"?: number;
        "uploadLabel"?: string;
        "uploadSuccess"?: boolean;
        "width"?: number;
    }
    interface ImageUploaderWrapper {
    }
    interface IntrinsicElements {
        "image-uploader": ImageUploader;
        "image-uploader-wrapper": ImageUploaderWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "image-uploader": LocalJSX.ImageUploader & JSXBase.HTMLAttributes<HTMLImageUploaderElement>;
            "image-uploader-wrapper": LocalJSX.ImageUploaderWrapper & JSXBase.HTMLAttributes<HTMLImageUploaderWrapperElement>;
        }
    }
}
